export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST'
}

export const signupConstants = {
    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_fAILURE: 'SIGNUP_FAILURE'
}

export const productConstants = {
    PRODUCT_REQUEST: 'PRODUCT_REQUEST',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_fAILURE: 'PRODUCT_FAILURE'
}

export const getProductsConstants = {
    GET_PRODUCT_REQUEST: 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_fAILURE: 'GET_PRODUCT_FAILURE'
}

export const deleteProductConstants = {
    DELETE_PRODUCT_REQUEST: 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE: 'DELETE_PRODUCT_FAILURE',
}